### ISSUE TITLE
crash on joining server

### ISSUE THREAD

**Issue by Zane2b2t** [lyricnight/infinity#3]
`[14:19:39]` [pool-2-thread-1/INFO]: {SKIN=com.mojang.authlib.minecraft.MinecraftProfileTexture@3be55306[url=http://textures.minecraft.net/texture/ddfb24ac2d6b69dd958d9979e57d7ec834774d65dea490f239a964679533c9eb,hash=ddfb24ac2d6b69dd958d9979e57d7ec834774d65dea490f239a964679533c9eb]}
[14:19:40] [Client thread/INFO]: Applying holder lookups
[14:19:40] [Client thread/INFO]: Holder lookups applied
[14:19:41] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.func_72939_s(World.java:1776) ~[amu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.entity.EntityPlayerSP.redirect$onUpdateWalkingPlayerRotationYaw$zzb000(EntityPlayerSP.java:1827) ~[bud.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:241) ~[bud.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196) ~[bud.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
	... 10 more
[14:19:42] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (infinity-v3-beta-7eb748d.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/1/23 2:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.client.entity.EntityPlayerSP.redirect$onUpdateWalkingPlayerRotationYaw$zzb000(EntityPlayerSP.java:1827)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:241)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.entity.EntityPlayerSP.redirect$onUpdateWalkingPlayerRotationYaw$zzb000(EntityPlayerSP.java:1827)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:241)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 103676
	Entity Name: AscendancyV47
	Entity's Exact location: 0.00, 131.00, 0.00
	Entity's Block location: World: (0,131,0), Chunk: (at 0,8,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)`

**Comment by lyricnight** [comment]
using old build, and remove newbase or some other mod

**Comment by Zane2b2t** [comment]
> using old build, and remove newbase or some other mod

standalone + i built it on my own

**Comment by lyricnight** [comment]
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)

**Comment by lyricnight** [comment]
idk i dont have the issue

**Comment by lyricnight** [comment]
@Zane2b2t try latest src issue should be fixed

**Comment by Zane2b2t** [comment]
> @Zane2b2t try latest src issue should be fixed

i will test l8r and inform u

**Comment by Zane2b2t** [comment]
> @Zane2b2t try latest src issue should be fixed

your software now works. only needed another issue to confirm it isnt something from my hardware! goodjob fixing!

**Comment by lyricnight** [comment]
issue never happened to me it’s something to do with your other mods tbh but whatever
