### ISSUE TITLE
crash on joining server

### ISSUE THREAD

**Issue by nukiz** [lyricnight/infinity#4]
java.lang.NullPointerException: Ticking entity
	at net.minecraft.client.entity.EntityPlayerSP.redirect$onUpdateWalkingPlayerRotationYaw$zzb000(EntityPlayerSP.java:1827)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:241)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

only this mod and optifine installed

**Comment by lyricnight** [comment]
this issue happens to some people and not for others, i don’t get it even with other mods 
I’ll have a look at it later

**Comment by lyricnight** [comment]
https://github.com/lyricnight/infinity/commit/8cd78792b72fc1c3d0004b15f31dadcb0202a754
^ try this build @nukiz
